name 'CookbookPHP7Kata'
maintainer 'Stacey Vetzal'
maintainer_email 'stacey@mojility.ca'
license 'MIT'
description 'Set up a basic PHP runtime environment for PHP Coaching kata'
long_description 'Set up a basic PHP runtime environment for PHP Coaching kata'
version '0.9.1'
